package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJuzi<M extends BaseJuzi<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setLength(java.lang.Integer length) {
		set("length", length);
	}
	
	public java.lang.Integer getLength() {
		return getInt("length");
	}

	public void setAuthor(java.lang.String author) {
		set("author", author);
	}
	
	public java.lang.String getAuthor() {
		return getStr("author");
	}

	public void setFrom(java.lang.String from) {
		set("from", from);
	}
	
	public java.lang.String getFrom() {
		return getStr("from");
	}

	public void setCategory(java.lang.String category) {
		set("category", category);
	}
	
	public java.lang.String getCategory() {
		return getStr("category");
	}

	public void setTags(java.lang.String tags) {
		set("tags", tags);
	}
	
	public java.lang.String getTags() {
		return getStr("tags");
	}

	public void setUpdateAt(java.util.Date updateAt) {
		set("updateAt", updateAt);
	}
	
	public java.util.Date getUpdateAt() {
		return get("updateAt");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("createAt", createAt);
	}
	
	public java.util.Date getCreateAt() {
		return get("createAt");
	}

	public void setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
	}
	
	public java.lang.Integer getAccountId() {
		return getInt("accountId");
	}

	public void setSourceType(java.lang.Integer sourceType) {
		set("sourceType", sourceType);
	}
	
	public java.lang.Integer getSourceType() {
		return getInt("sourceType");
	}

	public void setRemarkValue(java.lang.Integer remarkValue) {
		set("remarkValue", remarkValue);
	}
	
	public java.lang.Integer getRemarkValue() {
		return getInt("remarkValue");
	}

}
