package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJuziExt<M extends BaseJuziExt<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setJuziId(java.lang.Integer juziId) {
		set("juzi_id", juziId);
	}
	
	public java.lang.Integer getJuziId() {
		return getInt("juzi_id");
	}

	public void setApplyDesc(java.lang.String applyDesc) {
		set("applyDesc", applyDesc);
	}
	
	public java.lang.String getApplyDesc() {
		return getStr("applyDesc");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setHash(java.lang.String hash) {
		set("hash", hash);
	}
	
	public java.lang.String getHash() {
		return getStr("hash");
	}

	public void setEsIndexVer(java.lang.Integer esIndexVer) {
		set("es_index_ver", esIndexVer);
	}
	
	public java.lang.Integer getEsIndexVer() {
		return getInt("es_index_ver");
	}

}
