package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseJuzi;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Juzi extends BaseJuzi<Juzi> {


    //public static final Juzi dao = new Juzi();

    public JuziExt getExt() {
        Integer id = getId();
        return JuziExt.dao.findFirst("select * from juzi_ext where juzi_id=? limit 1", id);
    }
	
}
