package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseJuziExt;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JuziExt extends BaseJuziExt<JuziExt> {
	
}
