package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseJuziGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JuziGroup extends BaseJuziGroup<JuziGroup> {
	
}
